export const todoListDummyData = [
  {
    todo: "wash the dishes",
    status: "done",
    id: 1,
    date: new Date().toLocaleString(Date.now()),
    editDate: null,
    isGettingEdited: false,
  },
  {
    todo: "do my homework and go running",
    status: "inProgress",
    id: 2,
    date: new Date().toLocaleString(Date.now()),
    editedDate: null,
    isGettingEdited: false,
  },
  {
    todo: "watch the new react course online",
    status: "done",
    id: 3,
    date: new Date().toLocaleString(Date.now()),
    editedDate: null,
    isGettingEdited: false,
  },
  {
    todo: "finish the project that is for react",
    status: "none",
    id: 4,
    date: new Date().toLocaleString(Date.now()),
    editedDate: null,
    isGettingEdited: false,
  },
  {
    todo: "cleaning up my room and closet",
    status: "inProgress",
    id: 5,
    date: new Date().toLocaleString(Date.now()),
    editedDate: null,
    isGettingEdited: false,
  },
  {
    todo: "going to work and doing the tasks",
    status: "done",
    id: 6,
    date: new Date().toLocaleString(Date.now()),
    editedDate: null,
    isGettingEdited: false,
  },
];
